version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: docker
    ports:
      - 5432:5432
    volumes: 
      - /var/lib/docker/volumes/postgres:/var/lib/postgresql/data
